
name: 💡 Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: |
        A clear and concise description of what you want to happen.
        Consider including:
        - How this would benefit users
        - Any alternatives you've considered
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Can you provide examples of similar features in other projects?
      placeholder: Other projects solve this by...

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Critical (Blocking my work)
        - High (Would significantly improve my workflow)
        - Medium (Would be nice to have)
        - Low (Just an idea)
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request here
      placeholder: More details that might help understand the request better...

  - type: checkboxes
    id: terms
    attributes:
      label: Before Submitting
      description: Please confirm the following
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I am willing to help test this feature if implemented
          required: false